name: Deploy Node.js App to AWS EC2

on:
  workflow_run:
    workflows: ["Build and Test Node.js Application"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/ci-cd-key
          chmod 600 ~/.ssh/ci-cd-key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory or clone it if it doesn't exist
            if [ -d "~/node-ci-cd-5" ]; then
              cd ~/node-ci-cd-5 && git pull origin main
            else
              git clone https://github.com/Joy-it-code/node-ci-cd-5.git ~/node-ci-cd-5
              cd ~/node-ci-cd-5
            fi

            # Install dependencies
            npm install

            # Restart the application with PM2
            pm2 describe node-app > /dev/null 2>&1
            if [ $? -eq 0 ]; then
              pm2 restart node-app
            else
              pm2 start index.js --name "node-app"
            fi

            # Save PM2 process list and startup script
            pm2 save
            pm2 startup

    permissions:
      contents: read  # Only allow read access
      id-token: write # Needed for AWS authentication

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
